---
# need to set TMPDIR if we're using cleanenv
apptainer-args: -B $PWD,/tmp 
  -H $(mktemp -d) 
  --pwd $PWD 
  --env TMPDIR=/tmp 
  --env LC_ALL=C 
  --env BPA_APIKEY=${BPA_APIKEY}
  --containall --cleanenv --writable-tmpfs
apptainer-prefix: $APPTAINER_CACHEDIR
benchmark-extended: True
configfile:
  - profiles/local/workflow.config.yaml
cores: 8
printshellcmds: true
rerun-triggers:
  - mtime
use-apptainer: True
use-conda: False