manifest: "config/manifest.yaml"
containers:
  atol_genome_launcher: "docker://quay.io/biocontainers/atol-genome-launcher:0.7.4--pyhdfd78af_0"
  atol_qc_raw_ont: "docker://quay.io/biocontainers/atol-qc-raw-ont:0.2.1--pyhdfd78af_0"
  atol_qc_raw_pacbio: "docker://quay.io/biocontainers/atol-qc-raw-pacbio:0.1.1--pyhdfd78af_0"
  atol_qc_raw_shortread: "docker://quay.io/biocontainers/atol-qc-raw-shortread:0.3.1--pyhdfd78af_0"
  pigz: "docker://quay.io/biocontainers/pigz:2.8"
  wget: "docker://quay.io/biocontainers/wget:1.25.0"
